#!/bin/bash

BIN_DIR="$(git rev-parse --show-toplevel)"/bin
BINARY=$BIN_DIR/gotestsum
GOTESTSUM_VERSION=v1.10.0

if [ ! -f "$BINARY" ]; then
  GOBIN=$BIN_DIR go install gotest.tools/gotestsum@${GOTESTSUM_VERSION}
fi

$BINARY "$@"
